AWSTemplateFormatVersion: '2010-09-09'
Description: AWS Project Sample Template
Resources:
  MyLambdaFunction:
    Properties:
      CodeUri: s3://hasanganitestbuckets3/19c04a9e2dcb1959fdd1ab3b8f6e09ca
      Events:
        MyLambdaApi:
          Properties:
            Method: get
            Path: /mylambda
          Type: Api
        MyLambdaS3:
          Properties:
            Bucket:
              Ref: S3Bucket
            Events: s3:ObjectCreated:*
          Type: S3
      Handler: loggerTest.handler
      Runtime: nodejs8.10
    Type: AWS::Serverless::Function
  S3Bucket:
    Properties:
      BucketName: bucket-for-lambda-trigger-test
    Type: AWS::S3::Bucket
Transform: AWS::Serverless-2016-10-31
